name: use-resuable
on:
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      results: 
        description: The results of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    #secrets:
      #some-secret:
        #required: true
jobs:
  deploy:
    outputs: 
      outcome: ${{ steps.set-result.outputs.step.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: set result output
        id: set-result
        run: echo "step-result=SUCCESS" >> $GITHUB_OUTPUT